version: "3"

services:
  app:
    tty: true
    build:
      dockerfile: ./docker/Dockerfile
      context: .
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    tmpfs: ["/app/tmp", "/app/log"]

  db:
    image: mariadb:10.8
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  db-data:
